apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tawazun
  labels:
    app: mysql
    name: mysql-db
spec:
  type: ClusterIP
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
