apiVersion: v1
kind: Service
metadata:
  name: tawazun
  namespace: tawazun
  labels:
    name: tawazun-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: tawazun
    service: tawazun-svc
