apiVersion: v1
kind: Service
metadata:
  name: tawazun
  labels:
    app: tawazun
spec:
  type: LoadBalancer
  ports:
  - name: tawazun-service
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tawazun