apiVersion: v1
kind: Service
metadata:
  name: tawazun
  labels:
    app: tawazun
spec:
  type: NodePort
  ports:
  - name: tawazun-service
    port: 8080
    targetPort: 8080
    nodePort: 30454
    protocol: TCP
  selector:
    app: tawazun