apiVersion: v1
kind: Service
metadata:
  name: tawazun
  labels:
    app: tawazun
  namespace: tawazun
spec:
  type: LoadBAlancer
  ports:
  - name: tawazun-service
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tawazun