apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tawazun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: DB_tawazun
            - name: MYSQL_USER
              value: root
            - name: MUSQL_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql
          livenessProbe:
            httpGet:
              path: /probes
              port: 81
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /probes
              port: 81
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes
              port: 81
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: pv-ebs-db
              mountPath: /var/lib/mysql
      volumes:
        - name: pv-ebs-db
          persistentVolumeClaim:
            claimName: pvc-ebs-db