apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-app
  namespace: tawazun
  labels:
    app: tawazun
    service: tawazun-svc
    name: tawazun-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
      service: tawazun-svc
  template:
    metadata:
      labels:
        app: tawazun
        service: tawazun-svc
    spec:
      containers:
        - name: tawazun-app
          image: abdullahkimrigh/tawazun-sda-hackathon:0.1
          env:
            - name: DB_URL
              value: mysql
            - name: DB_PORT
              value: '3306'  
            - name: DB_NAME
              value: prodects  
            - name: DB_USERNAME
              value: root  
            - name: DB_PASSWORD
              value: root 
          resources: 
            requests: 
              memory: 250Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /probes
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /probes
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes
              port: 80
            failureThreshold: 30
            periodSeconds: 10
