apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-app
  namespace: tawazun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
  template:
    metadata:
      labels:
        app: tawazun
    spec:
      containers:
        - name: tawazun-app
          image: abdullahkimrigh/tawazun-sda-hackathon:0.1
          env:
            - name: DB_URL
              value: mysql
            - name: DB_PORT
              value: '3306'  
            - name: DB_NAME
              value: tawazun  
            - name: DB_USERNAME
              value: root  
            - name: DB_PASSWORD
              value: root 
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /probes
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /probes
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes
              port: 80
            failureThreshold: 30
            periodSeconds: 10